- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: include packages tasks
      include_tasks: tasks/packages.yml

    - name: include mariadb tasks
      include_tasks: tasks/mariadb.yml
