- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

    - name: upgrade all packages
      apt:
        upgrade: 'yes'
      changed_when: False

  tasks:
    - name: include tasks
      include_tasks: tasks/packages.yml